[Unit]
Description=Rover Controller Server
After=network.target

[Service]
User=walker
WorkingDirectory=/home/walker/Desktop/operators/src/python/robot
ExecStart=/usr/bin/python3 rover.py --distance --temperature --audio --ai --camera --camera-mount --oled --axles=2
Restart=always
Environment="OPENAI_API_KEY={{OPENAI_API_KEY}}"

[Install]
WantedBy=multi-user.target

