[Unit]
Description=Rover Live Stream Server
After=network.target

[Service]
User=walker
WorkingDirectory=/home/walker/Desktop/operators/src/python/robot
ExecStart=/usr/bin/python3 rover/servers/stream.py
Restart=always

[Install]
WantedBy=multi-user.target

